package advanced.exceptions;

import java.io.IOException;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) throws Exception {
        /*Scanner scanner = new Scanner(System.in);
while(true) {
    try {
        if (scanner.hasNextInt()) {
            int inputInt = scanner.nextInt();
            System.out.println("int -> " + inputInt);
        } else if (scanner.hasNextDouble()) {
            double inputDouble = scanner.nextDouble();
            System.out.println("double -> " + inputDouble);
        } else {
            int exInput = scanner.nextInt();
        }
    } catch (Exception e) {
        System.out.println("Hey! That's not a value! Try once more.");
        scanner.next();
    }
}*/

        String serviceName = "carWash";
        Executor ex = new Executor();



    }
}
